### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by emersoneber** [SqlToys/SqlFormatter-OBSOLETE#1]
I downloaded the fonts and several .pas files are missing. For example SqlLister.pas, SqlParser.pas. Among others.

**Comment by SqlToys** [comment]
Fonts? Check it again. I think I didnt use any special purpose fonts.
You asked for files that are shared with command line version (SqlFormat), those files are there.
Only SqlParser and SqlTokenizer are available as compiled wo. source code as I think they are ugly coded inside and requires many modifications.
Regards,
Tom.
